using Test
using Kraken

@testset "Kraken.jl LBM" begin
    include("test_lbm_basic.jl")
    include("test_poiseuille.jl")
    include("test_poiseuille_3d.jl")
    include("test_couette.jl")
    include("test_taylor_green.jl")
    include("test_thermal.jl")
    include("test_axisymmetric.jl")
    include("test_mrt.jl")
    include("test_species.jl")
    include("test_multiphase.jl")
    include("test_vof.jl")
    include("test_benchmark.jl")
    include("test_cavity.jl")
    include("test_cavity_3d.jl")
    include("test_cylinder.jl")
    include("test_expression.jl")
    include("test_kraken_parser.jl")
    include("test_simulation_runner.jl")
    include("test_stl.jl")
    include("test_krk_examples.jl")
    include("test_refinement.jl")
    include("test_curvilinear_mesh.jl")
    include("test_slbm.jl")
    include("test_slbm_taylor_green.jl")
    include("test_slbm_taylor_couette.jl")
    include("test_fused_trt_2d.jl")
    include("test_li_bb_2d.jl")
    include("test_taylor_couette_libb.jl")
    include("test_advection_prescribed.jl")
    include("test_krk_multiphase.jl")
    include("test_vtk_3d.jl")
    include("test_phasefield.jl")
    include("test_twophase_rheology.jl")
    include("test_postprocess.jl")
    include("test_rheology.jl")
    include("test_viscoelastic.jl")
end
