#!/usr/bin/env julia
# Extract module-level call graph from Kraken.jl source and emit Mermaid.
#
# Usage:  julia scripts/extract_callgraph.jl [output_path]
#
# Default output: docs/src/callgraph.md (overwrites)
#
# This is a regex/AST-light prototype. It extracts:
#   - Top-level `function` and `<name>(...) = ...` definitions per src/<module>/
#   - Calls to those defined names from other modules (cross-module edges only)
# It does NOT perform dispatch resolution — for that, graduate to MethodAnalysis.jl.
# False positives are possible on common short names (e.g. `init`, `update!`).
#
# Phase-2 TODO: replace with MethodAnalysis.jl once the package loads cleanly
# on the target branch (some dev branches have broken manifests).

const REPO_ROOT = abspath(joinpath(@__DIR__, ".."))
const SRC_DIR = joinpath(REPO_ROOT, "src")
const DEFAULT_OUT = joinpath(REPO_ROOT, "docs", "src", "callgraph.md")

const MODULES = ["drivers", "io", "kernels", "lattice", "refinement",
                 "multiblock", "curvilinear", "rheology"]

# Match `function name(...)` or `name(...) = ...` at top level.
# Captures the function name. Skips constructors (Capitalized first letter
# followed by `(...) = new(...)`) and operator overloads (Base.method).
const FUNC_DEF_RE = r"^\s*(?:function\s+|@inline\s+function\s+|@kernel\s+function\s+|(?:@__doc__\s+)?)(\w+!?)\s*[\(\{]"
# Match call sites: `name(...)` not preceded by `function ` or `.`
# Anchored by word-boundary on the left.
const CALL_RE = r"(?<![.\w])(\w+!?)\("

# Skip these very common names from cross-module edges (noise reduction).
const NOISE_NAMES = Set([
    "size", "length", "zeros", "ones", "fill", "similar", "eltype", "axes",
    "println", "print", "show", "string", "Symbol", "Int", "Float64", "Float32",
    "abs", "min", "max", "sum", "prod", "any", "all", "isnothing", "isa",
    "get", "haskey", "push!", "pop!", "empty!", "copy", "deepcopy",
    "view", "reshape", "vec", "collect", "first", "last",
    "error", "throw", "@assert", "@info", "@warn", "@debug",
    "Tuple", "Vector", "Array", "Matrix", "NamedTuple", "Dict", "Set",
    # Module names themselves shouldn't appear as call targets here
    "Kraken", "Base", "Core",
])

"Module that owns a given file (returns module name or `nothing`)."
function module_of(path::AbstractString)
    rel = relpath(path, SRC_DIR)
    parts = splitpath(rel)
    if length(parts) >= 2 && parts[1] in MODULES
        return parts[1]
    end
    return nothing  # top-level file like Kraken.jl, simulation_runner.jl
end

"Walk src/ and collect (module, function_name, file) tuples."
function collect_definitions()
    defs = Dict{String, String}()  # function_name → module
    for (root, _, files) in walkdir(SRC_DIR)
        for f in files
            endswith(f, ".jl") || continue
            path = joinpath(root, f)
            mod = module_of(path)
            isnothing(mod) && continue
            for line in eachline(path)
                m = match(FUNC_DEF_RE, line)
                m === nothing && continue
                name = m.captures[1]
                name in NOISE_NAMES && continue
                # First definition wins (avoid overwriting with later overloads in other modules)
                get!(defs, name, mod)
            end
        end
    end
    return defs
end

"For each file in src/, collect cross-module calls (caller_mod → callee_mod)."
function collect_edges(defs::Dict{String,String})
    edges = Dict{Tuple{String,String}, Int}()  # (caller_mod, callee_mod) → count
    for (root, _, files) in walkdir(SRC_DIR)
        for f in files
            endswith(f, ".jl") || continue
            path = joinpath(root, f)
            caller = module_of(path)
            isnothing(caller) && continue
            content = read(path, String)
            for m in eachmatch(CALL_RE, content)
                name = m.captures[1]
                callee = get(defs, name, nothing)
                isnothing(callee) && continue
                callee == caller && continue  # intra-module, skip
                edges[(caller, callee)] = get(edges, (caller, callee), 0) + 1
            end
        end
    end
    return edges
end

"Emit Mermaid flowchart from the edges."
function emit_mermaid(edges::Dict{Tuple{String,String}, Int}, defs::Dict{String,String})
    io = IOBuffer()
    println(io, "<!-- Auto-generated by scripts/extract_callgraph.jl — do NOT edit by hand. -->")
    println(io, "<!-- Regenerate with: julia scripts/extract_callgraph.jl -->")
    println(io)
    println(io, "# Auto-generated call graph")
    println(io)
    println(io, "Cross-module function-call edges extracted from `src/` by static regex.")
    println(io, "Edge weight = number of call sites. Intra-module calls are not shown.")
    println(io, "Compare against the curated [Architecture page](architecture.md) — if")
    println(io, "the two disagree, a PR has either added an undocumented coupling or")
    println(io, "this graph needs regeneration.")
    println(io)
    # Summary stats
    n_funcs = length(defs)
    n_edges = length(edges)
    println(io, "**Stats**: ", n_funcs, " functions across ", length(MODULES),
            " modules, ", n_edges, " cross-module call-site pairs.")
    println(io)
    println(io, "## Module-level call graph")
    println(io)
    println(io, "```mermaid")
    println(io, "flowchart LR")
    for m in MODULES
        println(io, "    ", m, "[\"", m, "/\"]")
    end
    # Emit edges sorted for stability
    for ((caller, callee), n) in sort(collect(edges), by = first)
        label = n > 1 ? string(" -- \"", n, "×\" --> ") : " --> "
        println(io, "    ", caller, label, callee)
    end
    println(io, "```")
    println(io)
    # Detailed per-module table
    println(io, "## Functions defined per module")
    println(io)
    by_mod = Dict{String, Vector{String}}()
    for (name, mod) in defs
        push!(get!(by_mod, mod, String[]), name)
    end
    for m in MODULES
        names = sort(get(by_mod, m, String[]))
        println(io, "### ", m, "/")
        println(io)
        if isempty(names)
            println(io, "_(no top-level definitions detected)_")
        else
            println(io, "Top-level definitions (", length(names), "): ",
                    join(("`" .* names .* "`")[1:min(end, 30)], ", "),
                    length(names) > 30 ? ", … (truncated)" : "")
        end
        println(io)
    end
    return String(take!(io))
end

function main()
    out_path = length(ARGS) >= 1 ? ARGS[1] : DEFAULT_OUT
    println("[extract_callgraph] scanning ", SRC_DIR)
    defs = collect_definitions()
    println("[extract_callgraph] found ", length(defs), " top-level definitions")
    edges = collect_edges(defs)
    println("[extract_callgraph] found ", length(edges), " cross-module edge pairs")
    md = emit_mermaid(edges, defs)
    mkpath(dirname(out_path))
    write(out_path, md)
    println("[extract_callgraph] wrote ", out_path, " (", length(md), " bytes)")
end

# Run when invoked from CLI
if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
