# view/generate_doc_figures.jl
#
# Purpose
# -------
# Standalone driver that produces the PNG figures referenced by the example
# pages under `docs/src/examples/*.jl`. Each figure is generated by running
# the matching `.krk` case via `Kraken.run_simulation`, then handing the
# result to the KrakenView figure primitives (`heatmap_field`,
# `profile_plot`) and finally writing the PNG through `save_figure`.
#
# How to run
# ----------
#     julia --project=view view/generate_doc_figures.jl
#
# The script is idempotent: re-running it overwrites the target files with
# the same content. Wall-clock is kept under ~10 min on CPU by using
# moderate `max_steps` overrides per case (illustrative figures, not full
# validation runs).
#
# Cases covered (in-scope example pages 01–09)
# --------------------------------------------
#   01_poiseuille_2d      -> poiseuille_profile.png        (profile + analytical)
#   02_couette_2d         -> couette_profile.png           (profile + analytical)
#   03_taylor_green_2d    -> taylor_green_vorticity.png    (heatmap, vorticity)
#   04_cavity_2d          -> cavity_centerlines.png        (profile ux along y)
#   05_cavity_3d          -> cavity_3d_umag.png            (heatmap, |u| mid-z)
#   06_cylinder_2d        -> cylinder_umag.png             (heatmap, |u|)
#   07_heat_conduction    -> heat_profile.png              (profile T along x)
#   08_rayleigh_benard    -> rayleigh_benard_temperature.png (heatmap, T)
#   09_hagen_poiseuille   -> hagen_poiseuille_profile.png  (profile uz vs r)
#
# Skipped
# -------
#   10_krk_config               - tutorial page, no single-case figure
#   20_grid_refinement_cavity   - .krk runner errors on non-thermal refined
#                                 cases (deferred to v0.2.0)

using Pkg
Pkg.activate(@__DIR__)

using Printf
using CairoMakie
using Kraken
using KrakenView

const EXAMPLES_DIR = abspath(joinpath(@__DIR__, "..", "examples"))
const FIG_DIR      = abspath(joinpath(@__DIR__, "..", "docs", "src", "assets", "figures"))
isdir(FIG_DIR) || mkpath(FIG_DIR)

"Safe run: returns (result, seconds) or (nothing, 0.0) on failure."
function _safe_run(path; max_steps=nothing)
    try
        t0 = time()
        r = Kraken.run_simulation(path; max_steps=max_steps)
        return (r, time() - t0)
    catch err
        @warn "run_simulation failed" path err
        return (nothing, 0.0)
    end
end

"Compute |u| from ux, uy (and optional uz)."
_umag(ux, uy) = sqrt.(ux .^ 2 .+ uy .^ 2)
_umag(ux, uy, uz) = sqrt.(ux .^ 2 .+ uy .^ 2 .+ uz .^ 2)

"Compute 2D vorticity ω_z = ∂v/∂x − ∂u/∂y via central differences."
function _vorticity(ux, uy)
    Nx, Ny = size(ux)
    ω = zeros(eltype(ux), Nx, Ny)
    @inbounds for j in 2:Ny-1, i in 2:Nx-1
        ω[i, j] = 0.5 * (uy[i+1, j] - uy[i-1, j]) -
                  0.5 * (ux[i, j+1] - ux[i, j-1])
    end
    return ω
end

summary = Dict{String,Any}()
timings = Dict{String,Float64}()
t_total0 = time()

# ---------------------------------------------------------------------------
# 01 Poiseuille — profile + analytical parabola
# ---------------------------------------------------------------------------
let name = "poiseuille_profile.png"
    r, dt = _safe_run(joinpath(EXAMPLES_DIR, "poiseuille.krk"); max_steps=8000)
    if r === nothing
        summary[name] = "skipped (run failure)"
    else
        ux = r.ux
        Nx, Ny = size(ux)
        # Use an analytical Poiseuille parabola normalized to match peak:
        u_max = maximum(ux)
        ref = y -> begin
            ymin, ymax = 1, Ny
            4u_max * (y - ymin) * (ymax - y) / (ymax - ymin)^2
        end
        fig = profile_plot(ux, :vertical;
                           axis_value=cld(Nx, 2), reference=ref,
                           title="Poiseuille velocity profile",
                           xlabel="y (lattice)", ylabel="u_x",
                           ref_label="analytical parabola",
                           label="LBM")
        save_figure(fig, joinpath(FIG_DIR, name))
        summary[name] = "OK"
        timings[name] = dt
    end
end

# ---------------------------------------------------------------------------
# 02 Couette — profile + linear analytical
# ---------------------------------------------------------------------------
let name = "couette_profile.png"
    r, dt = _safe_run(joinpath(EXAMPLES_DIR, "couette.krk"); max_steps=6000)
    if r === nothing
        summary[name] = "skipped (run failure)"
    else
        ux = r.ux
        Nx, Ny = size(ux)
        u_top = maximum(ux)
        ref = y -> u_top * (y - 1) / (Ny - 1)
        fig = profile_plot(ux, :vertical;
                           axis_value=cld(Nx, 2), reference=ref,
                           title="Couette velocity profile",
                           xlabel="y (lattice)", ylabel="u_x",
                           ref_label="analytical (linear)",
                           label="LBM")
        save_figure(fig, joinpath(FIG_DIR, name))
        summary[name] = "OK"
        timings[name] = dt
    end
end

# ---------------------------------------------------------------------------
# 03 Taylor-Green — vorticity heatmap
# ---------------------------------------------------------------------------
let name = "taylor_green_vorticity.png"
    r, dt = _safe_run(joinpath(EXAMPLES_DIR, "taylor_green.krk"); max_steps=2000)
    if r === nothing
        summary[name] = "skipped (run failure)"
    else
        ω = _vorticity(r.ux, r.uy)
        fig = heatmap_field(ω; field_name="ω_z", colormap=:balance,
                            title="Taylor-Green vortices — vorticity")
        save_figure(fig, joinpath(FIG_DIR, name))
        summary[name] = "OK"
        timings[name] = dt
    end
end

# ---------------------------------------------------------------------------
# 04 Lid-driven cavity — ux centreline profile
# ---------------------------------------------------------------------------
let name = "cavity_centerlines.png"
    r, dt = _safe_run(joinpath(EXAMPLES_DIR, "cavity.krk"); max_steps=8000)
    if r === nothing
        summary[name] = "skipped (run failure)"
    else
        ux = r.ux
        Nx, _ = size(ux)
        fig = profile_plot(ux, :vertical;
                           axis_value=cld(Nx, 2),
                           title="Lid-driven cavity — u_x along vertical centreline",
                           xlabel="y (lattice)", ylabel="u_x",
                           label="LBM")
        save_figure(fig, joinpath(FIG_DIR, name))
        summary[name] = "OK"
        timings[name] = dt
    end
end

# ---------------------------------------------------------------------------
# 05 Cavity 3D — |u| at mid-z plane
# ---------------------------------------------------------------------------
let name = "cavity_3d_umag.png"
    r, dt = _safe_run(joinpath(EXAMPLES_DIR, "cavity_3d.krk"); max_steps=2000)
    if r === nothing
        summary[name] = "skipped (run failure)"
    else
        ux = r.ux; uy = r.uy
        uz = hasproperty(r, :uz) ? r.uz : zero(ux)
        u = _umag(ux, uy, uz)
        Nx, Ny, Nz = size(u)
        slice = u[:, :, cld(Nz, 2)]
        fig = heatmap_field(slice; field_name="|u|",
                            title="3D lid cavity — |u| at mid-z plane")
        save_figure(fig, joinpath(FIG_DIR, name))
        summary[name] = "OK"
        timings[name] = dt
    end
end

# ---------------------------------------------------------------------------
# 06 Cylinder flow — |u| with solid mask
# ---------------------------------------------------------------------------
let name = "cylinder_umag.png"
    r, dt = _safe_run(joinpath(EXAMPLES_DIR, "cylinder.krk"); max_steps=4000)
    if r === nothing
        summary[name] = "skipped (run failure)"
    else
        u = _umag(r.ux, r.uy)
        mask = hasproperty(r, :is_solid) ? r.is_solid : nothing
        fig = heatmap_field(u; field_name="|u|",
                            geometry=mask,
                            title="Flow past a cylinder — |u|")
        save_figure(fig, joinpath(FIG_DIR, name))
        summary[name] = "OK"
        timings[name] = dt
    end
end

# ---------------------------------------------------------------------------
# 07 Heat conduction — T(x) profile
# ---------------------------------------------------------------------------
let name = "heat_profile.png"
    r, dt = _safe_run(joinpath(EXAMPLES_DIR, "heat_conduction.krk"); max_steps=4000)
    if r === nothing
        summary[name] = "skipped (run failure)"
    else
        T = hasproperty(r, :Temp) ? r.Temp :
            hasproperty(r, :T) ? r.T : nothing
        if T === nothing
            summary[name] = "skipped (no Temp field)"
        else
            _, Ny = size(T)
            fig = profile_plot(T, :horizontal;
                               axis_value=cld(Ny, 2),
                               title="Heat conduction — T along x at mid-y",
                               xlabel="x (lattice)", ylabel="T",
                               label="LBM")
            save_figure(fig, joinpath(FIG_DIR, name))
            summary[name] = "OK"
            timings[name] = dt
        end
    end
end

# ---------------------------------------------------------------------------
# 08 Rayleigh-Bénard — T heatmap
# ---------------------------------------------------------------------------
let name = "rayleigh_benard_temperature.png"
    r, dt = _safe_run(joinpath(EXAMPLES_DIR, "rayleigh_benard.krk"); max_steps=3000)
    if r === nothing
        summary[name] = "skipped (run failure)"
    else
        T = hasproperty(r, :Temp) ? r.Temp :
            hasproperty(r, :T) ? r.T : nothing
        if T === nothing
            summary[name] = "skipped (no Temp field)"
        else
            fig = heatmap_field(T; field_name="T", colormap=:thermal,
                                title="Rayleigh-Bénard — temperature field")
            save_figure(fig, joinpath(FIG_DIR, name))
            summary[name] = "OK"
            timings[name] = dt
        end
    end
end

# ---------------------------------------------------------------------------
# 09 Hagen-Poiseuille — uz(r) profile
# ---------------------------------------------------------------------------
let name = "hagen_poiseuille_profile.png"
    r, dt = _safe_run(joinpath(EXAMPLES_DIR, "hagen_poiseuille.krk"); max_steps=6000)
    if r === nothing
        summary[name] = "skipped (run failure)"
    else
        uz = hasproperty(r, :uz) ? r.uz :
             hasproperty(r, :ux) ? r.ux : nothing
        if uz === nothing
            summary[name] = "skipped (no uz field)"
        else
            Nz, _ = size(uz)
            uz_max = maximum(uz)
            Nr = size(uz, 2)
            ref = r_ -> begin
                rr = (r_ - 1) / (Nr - 1)  # normalized 0..1
                uz_max * (1 - rr^2)
            end
            fig = profile_plot(uz, :vertical;
                               axis_value=cld(Nz, 2), reference=ref,
                               title="Hagen-Poiseuille — u_z along radius",
                               xlabel="r (lattice)", ylabel="u_z",
                               ref_label="analytical (parabolic)",
                               label="LBM")
            save_figure(fig, joinpath(FIG_DIR, name))
            summary[name] = "OK"
            timings[name] = dt
        end
    end
end

t_total = time() - t_total0

println("\n=== Phase 4.3 Pass B — figure generation summary ===")
for (k, v) in sort(collect(summary))
    tstr = haskey(timings, k) ? @sprintf("%6.1fs", timings[k]) : "      "
    println("  ", rpad(k, 38), "  ", v, "   ", tstr)
end
println("Total wall-clock: ", round(t_total; digits=1), " s")
println("Figures written to: ", FIG_DIR)
